// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCuQYBZ-zRgjXwkLgoVMA4sjQLKTNac4E',
    appId: '1:24753168209:web:f19b761b64fe0fd8d43d70',
    messagingSenderId: '24753168209',
    projectId: 'avoidplasticapp',
    authDomain: 'avoidplasticapp.firebaseapp.com',
    storageBucket: 'avoidplasticapp.firebasestorage.app',
    measurementId: 'G-MJFY55FHZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd9RRCwhM_4oMeC2W9LPlvHKsCRaqjte4',
    appId: '1:24753168209:android:c0e3c73c4166a602d43d70',
    messagingSenderId: '24753168209',
    projectId: 'avoidplasticapp',
    storageBucket: 'avoidplasticapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy4Vb83sqjw1KN-AT3Et4CwHM9UXarNQQ',
    appId: '1:24753168209:ios:28e88d34e309e8a1d43d70',
    messagingSenderId: '24753168209',
    projectId: 'avoidplasticapp',
    storageBucket: 'avoidplasticapp.firebasestorage.app',
    androidClientId: '24753168209-mcariolfhj7f3hr54262cs1d3lp5bjh3.apps.googleusercontent.com',
    iosClientId: '24753168209-gg03p7lnv020dtau5ra2550joabca623.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy4Vb83sqjw1KN-AT3Et4CwHM9UXarNQQ',
    appId: '1:24753168209:ios:28e88d34e309e8a1d43d70',
    messagingSenderId: '24753168209',
    projectId: 'avoidplasticapp',
    storageBucket: 'avoidplasticapp.firebasestorage.app',
    androidClientId: '24753168209-mcariolfhj7f3hr54262cs1d3lp5bjh3.apps.googleusercontent.com',
    iosClientId: '24753168209-gg03p7lnv020dtau5ra2550joabca623.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQbVuXAwFfVQIrJecLBAlJj0JA-em5go4',
    appId: '1:24753168209:web:d534e34ff8c59ccad43d70',
    messagingSenderId: '24753168209',
    projectId: 'avoidplasticapp',
    authDomain: 'avoidplasticapp.firebaseapp.com',
    storageBucket: 'avoidplasticapp.firebasestorage.app',
    measurementId: 'G-ZHXE6PPWMX',
  );

}